// The UI's French copy. Violation ids are never translated: where no field
// message maps an id, the id is shown as received.

export const COPY = {
  title: 'Personnages joueurs',
  loading: 'Chargement des PJ…',
  empty: 'Aucun PJ pour le moment. Ajoutez le premier ci-dessous.',
  notFound: 'Campagne introuvable.',
  noCampaign: 'Aucune campagne sélectionnée.',
  readError: 'La liste des PJ n’a pas pu être lue.',
  stale: 'La liste affichée est peut-être en retard sur les dernières modifications.',
  colName: 'Nom',
  colClass: 'Classe',
  colLevel: 'Niveau',
  labels: { nom: 'Nom', classe: 'Classe', niveau: 'Niveau' },
  addTitle: 'Ajouter un PJ',
  editTitle: 'Modifier un PJ',
  add: 'Ajouter',
  edit: 'Modifier',
  save: 'Enregistrer',
  archive: 'Archiver',
  archiving: 'Archivage…',
  close: 'Fermer',
  sending: 'Envoi en cours…',
  transport: 'La connexion au serveur a été interrompue. Si la commande est partie, elle ne sera appliquée qu’une fois.',
  yourValue: 'Votre modification',
  aheadValue: 'Valeur déjà appliquée',
  awaitingTitle: 'Votre modification attend votre confirmation.',
  leaveHint: 'Vous pouvez fermer ce formulaire : sans confirmation, la modification expire au bout de 24 h et rien ne change.',
  confirm: 'Confirmer ma modification',
  cancel: 'Annuler ma modification',
  expired: 'La modification a expiré : rien n’a changé.',
  cancelled: 'La modification a été annulée : rien n’a changé.',
  refused: (id: string | null): string => (id === null ? 'Refusé.' : `Refusé : ${id}`),
} as const;
